version: '3.8'

services:
  webapi:
    image: webapi
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:80
      ASPNETCORE_HTTPS_PORT: 443