block-list-secret-scan: []
branch: master
custom-tool-name: Checkov
directory:
  - .
evaluate-variables: true
external-modules-download-path: .external_modules
mask: []
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_AZURE_109
  - CKV_AZURE_189
  - CKV2_AZURE_32
summary-position: top
