name: scan
on:
  pull_request:
    branches:
      - master
    paths:
      - "App/**/*.cs"
      - "App/**/*.csproj"
      - "Dockerfile"
      - ".github/workflows/scan.yml"
  workflow_call:
    inputs:
      severities:
        description: "Comma-separated list of severities to scan for: critical, high, medium, low, unspecified"
        required: true
        type: string
        default: critical,high
      package-types:
        description: "Comma-separated list of package types to scan for: e.g. apk, nuget"
        required: true
        type: string
        default: "nuget"
  workflow_dispatch:
    inputs:
      severities:
        description: "Comma-separated list of severities to scan for: critical, high, medium, low, unspecified"
        required: true
        type: string
        default: critical,high
      package-types:
        description: "Comma-separated list of package types to scan for: e.g. apk, nuget"
        required: true
        type: string
        default: "nuget"
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      IMAGE_TAG: bitcoin-web-api:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.IMAGE_TAG }}
      - name: Scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: local://${{ env.IMAGE_TAG }}
          only-severities: ${{ inputs.severities || 'critical,high' }}
          only-package-types: ${{ inputs.package-types || ''}}
          only-fixed: true
          exit-code: true
