name: test
on:
  push:
    branches:
      - master
    paths:
      - "**.cs"
      - "**.csproj"
      - "!.github/**"
      - ".github/workflows/test.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "**.cs"
      - "**.csproj"
      - "!.github/**"
      - ".github/workflows/test.yaml"
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        dotnet: ["8.0.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build app
        run: dotnet build
      - name: Test
        run: dotnet test
